Basic expression parsing
jensjeflensje/websk pull request #13
Opened 2021-10-31 10:16 UTC by SkyCraft78

This pull request offer the way to parse expression directly in a template file:

```applescript
define webserver:
	port: 8000
	on request:
		set {_version} to skript version
		return the template file "property.html"
```

With template:
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1>
		Expression var example
	</h1>
	<p>{{version}}
	{{show avatar of bot named "bot"}}
	{{show size of members of guild with id "818182471140114432"}}</p>
</body>
</html>
```

Show:
![image](https://user-images.githubusercontent.com/50667548/139577886-fee60329-5027-4ce8-97ba-42002fd59531.png)

I currently set the special mark as `show`, but you can change it at any time as you like ^^
Moreover, it should parse expression according to the current event, which means the local variables and the event values will be set and usable.

2021-10-31 10:34 UTC, jensjeflensje requested changes
Thanks for making this! One little change though ;)

2021-10-31 10:34 UTC, jensjeflensje commented on src/main/java/dev/jensderuiter/websk/skript/expression/ExprLoadFile.java
> +                        break;
This should be continue

2021-10-31 14:05 UTC, SkyCraft78 commented on src/main/java/dev/jensderuiter/websk/skript/expression/ExprLoadFile.java
> +                        break;
Oh yes you've right sorry x)

2021-10-31 14:45 UTC, SkyCraft78 commented
This new commit brings a lot of new things, as the commit mention:
* You can now use the variable inside `show` part, for example, `show "%_test%"` or `show "%_players::*%" in lower case` (combining with expressions)
* If any errors happen while compiling through mustache factory, retrieve the file's content or parsing expressions, a custom error page will appear instead of throwing an exception in the console.
* Allowed a more user-friendly string method for variables that return a list (Skript return a map) by listing values and not indices.

2021-11-02 18:17 UTC, SkyCraft78 commented
This new commit completely reworks the parser and is currently from our side only.
Made it not static, to possibly make multiple instances of the parser, but you can change it if you want.
Also changed the way to get file's content, more optimized one.

** What can be done?**

* Show variable with its name only > `{{var_name}}` (list too `{{var_name::*}}`)
* Show expression based on the event > `{{show %expr%}}` aka `{{show size of all players}}` (surround variable with `%%` like `{{show name of %_player%}}`)
* Loop accept both list variables & array expressions (`{{loop members::*}}` or `{{loop members of guild with id "XXX"}}`)
* Get back the loop-value of the current loop with `loop entity` expression (aka `{{show discord name of loop entity}}`)

**What can __not__ be done (yet)?**

* Have multiple lists inside themselves (was working on it, idk where it could come from but will continue tomorrow)
* execute effect within the `{{}}` codes (if you want so, why not adding like `{{execute <effect>}}` ?)

2021-11-02 18:38 UTC, jensjeflensje approved these changes

2021-11-02 18:52 UTC, merged